print("hello , this is python code ")
print("added this line in vscode")
print("Hii , bukubu ")
print("THis is for checking pull")
print("Bye")
print("commit check-1")
print("commit check - 2")
print("commit check-3")
